// Code generated by gen.go; DO NOT EDIT.
// source: queues.yml

package rabbitmq

import (
	"fmt"

	"github.com/groundctl/groundctl/internal/config"
	amqp "github.com/rabbitmq/amqp091-go"
)

// DefaultClient represents and AMQP 0-9-1 client for the vhost ""
//
// Configure credentials for this vhost client in the config
type DefaultClient struct {
	*amqp.Connection
}

// Creates a new AMQP 0-9-1 client for the "" vhost
func NewDefaultClient() (*DefaultClient, error) {
	creds, ok := config.RabbitMQ.Credentials["default"]
	if !ok {
		return nil, fmt.Errorf("configuration missing key \"rabbitmq.credentials.default\"")
	}
	conn, err := openConnection("", creds.Username, creds.Password)
	if err != nil {
		return nil, fmt.Errorf("failed to open rabbitmq connection: %w", err)
	}
	return &DefaultClient{
		conn,
	}, nil
}
